name = "TriangularDislocation"
uuid = "85f86d6d-3fe5-451f-a6a5-17fbf251aa87"
version = "0.1.0"
authors = ["limkjae <limkjae@naver.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.12.1"
LinearAlgebra = "1.12.0"
PrecompileTools = "1.3.3"
